// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PressAltTab() {
  return window['go']['main']['App']['PressAltTab']();
}

export function PressCtrlV() {
  return window['go']['main']['App']['PressCtrlV']();
}
